[projects."git-codecommit.us-east-1.amazonaws.com/v1/repos/athenis"]
approved-commands = [
    "just platform check",
    "just platform verify",
    "just platform verify && just console check",
]

[projects."github.com/christian-deleon/athenis"]
approved-commands = [
    "just platform check",
]

[projects."gitlab.devops.athenis.io/platform/athenis"]
approved-commands = [
    "just platform verify",
    "just platform check",
]
