[projects."github.com/christian-deleon/athenis"]
approved-commands = [
    "just platform check",
]

[projects."gitlab.devops.athenis.io/platform/athenis"]
approved-commands = [
    "just platform verify",
    "just platform check",
]
