---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
    - name: Git clone podman_install role
      ansible.builtin.git:
        repo: https://gitlab.com/devops9483002/ansible/roles/podman_install.git
        dest: ~/.ansible/roles/podman_install
        version: main
