---
- name: Install and Configure Latest Vim
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  tasks:
    - name: Add the Vim repository on Ubuntu
      ansible.builtin.apt_repository:
        repo: ppa:jonathonf/vim
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Vim
      ansible.builtin.package:
        name: vim
        state: present
