---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
    - name: Update dotfiles
      ansible.builtin.git:
        repo: ~/dotfiles
        dest: ~/dotfiles
        recursive: true
        update: true
        version: main
      ignore_errors: true

- name: Update packages
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  roles:
    - ~/.ansible/roles/os_update
